### ISSUE TITLE
Support for 5.05

### ISSUE THREAD

**Issue by ghost** [BISOON/ps4-api-server#2]
Would be great if 5.05 support could be added for this and for the PS4LIB.

**Comment by 0xwal** [comment]
I will try my best soon, I need to have my PS4 back to get it done and test my commits .. Thanks

**Comment by Findusthehaxor** [comment]
This could be quite usefull https://github.com/ExodusSecurity/PS4Offsets-With-Payloads

**Comment by ReazerDev** [comment]
Did you port it yet? Or are there any working ports, I can't find any.

**Comment by 0xwal** [comment]
try this branch https://github.com/BISOON/PS4-API-SERVER/tree/temp-5.05
